# Example YAML config to weigh syntax options.
itemType: post
field_map:
  # Example 1. Easy use case: destination and source properties expect a string.
  # This may or may not be the most common use case.
  destProperty: drupal_property
  # Example 2. Structured, but complex.
  # - Destination structure requires source property normalization into
  #   something other than a string.
  # - Here we explicitly define a normalizer.
  # - This is more structured, but would make the YAML config much longer. Our
  #   class would also need to distinguish the difference between these expected
  #   YAML maps and nested YAML maps conforming to any destination structure
  #   (like customFields), which we already support.
  destProperty2:
    normalizer: program
    sourcePropertyTrail:
      - referenceProperty
      - propertyOnLastReferencedEntity
      - columnFooOnLastProperty
  # Example 3. Simple.
  # - No need to specify the normalizer if we pass the destination property keys
  #   (this way each normalizer classes can define which destination properties
  #   it supports).
  # - No need to pass the trail if we use dot-notation syntax.
  destProperty3: referenceProperty.propertyOnLastReferencedEntity.columnFooOnLastProperty
